version: '3'
services:
  nginx-website:
    image: nginx:1.13.3-alpine
    container_name: nginx-website
    ports:
      - 3456:80
    volumes:
      - ./output:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
