baseurl = "https://adrianastley.com"
languageCode = "en-us"
title = "Adrian Astley"
# Enable comments by entering your Disqus shortname
disqusShortname = "adrianastley-com"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
preservetaxonomynames = true


[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
    # Tell me who you are
    author = "Adrian Astley"
    copyright  = "Adrian Astley"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"
	

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = true
    label  = "Blog"
    link   = "blog"

[[params.menu]]
    before = true
    label  = "Projects"
    link   = "projects/"
	
[[params.menu]]
    before = true
    label  = "Resume"
    link   = "resume/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/RichieSams"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "RichieSams"
    twitter         = "adastley"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = false
    categories = true
    tags = false
    tag_cloud = false
